version: '3'
services:
  twilio-sms-sender:
    image: ${DOCKER_USER}/${IMAGE_NAME}:${TAG}
    container_name: ${IMAGE_NAME}
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER_FROM=${TWILIO_PHONE_NUMBER_FROM}
    build:
      context: .
      args:
        JAR_FILE: target/${IMAGE_NAME}-${TAG}.jar